---

- name: Cisco Wired Campus Design
  hosts: 192.168.0.4
  gather_facts: false
  connection: local

  vars:
    cli:
      username: david
      password: cisco

handlers:
  - name: send mail
      mail:
      host: xxx.xxx.xxx.xxx
      port: xxxxxxxx
      sender: riyad1504@hotmail.co.uk
      to: Riyad Ali <riyad15044@hotmail.co.uk>
      subject: Report for { { ansible_hostname } }
      body: 'Server { { ansible_hostname } } has bene updated'
    delegate_to: localhost

      register: print_output

    -  debug: var=print_output
