---

- name: Cisco Wired Campus Design
  hosts: S1
  gather_facts: false
  connection: local

  vars:
    cli:
      username: david
      password: cisco

  tasks:
    - name: EMAIL
      mail:
        host: smtp.gmail.com
        port: 587
        username: adomijan45@gmail.com
        password: Gtdvwre884!
        to: recipient-name <adomijan45@gmail.com>
        subject: Ansible Report
        attach: flash:config.text
        body: System [[ ansible_hostname ]] has been successfully provisioned.
      delegate_to: localhost



      register: print_output

    -  debug: var=print_output
