---

- name: Cisco Wired Campus Design
  hosts: 192.168.0.4
  gather_facts: false
  connection: local

  vars:
    cli:
      username: david
      password: cisco

handlers:
  - name: send mail
      mail:
      host: 192.168.0.4
      port: 25
      sender: adomijan45@gmail.com
      to: Alex Domijan <adomijan45@gmail.com>
      subject: Report for { { ansible_hostname } }
      body: 'Server { { ansible_hostname } } has been updated'
    delegate_to: localhost

      register: print_output

    -  debug: var=print_output
