---
- name: Backup show run (enable mode commands)
  hosts: Switch
  gather_facts: false
  connection: local

  vars:
    cli:
      username: david
      password: cisco

  tasks:
    - name: run enable level commands
      ios_command:
        username: david
        password: cisco
        authorize: yes
        commands:
          - wr
        timeout: 40

      register: print_output

    -  debug: var=print_output.stdout_lines
