---

- name: Cisco Wired Campus Design
  hosts: all
  gather_facts: false
  connection: local

  vars:
    cli:
      username: david
      password: cisco

  tasks:
    - name: Global config settings
      ios_config:
        provider: "{{ cli }}"
        lines:
          - clock timezone PST -8
          - clock summer-time PDT recurring
          - service timestamps debug datetime msec localtime
          - service timestamps log datetime msec localtime

          - "vlan 1,10,20,30,40,50,100,101"




      register: print_output

    -  debug: var=print_output

    - name: NTP Server
      ios_config:
        provider: "{{ cli }}"
        lines:
          - ntp server 192.168.35.3

      register: print_output

    -  debug: var=print_output
